baseURL = 'https://anabasis.github.io'
locale = 'ko-kr'
title = 'CaptainSnail 기술 블로그'
theme = "PaperMod"
#theme = "hugo-theme-stack"
#theme = "hugo-coder"
#theme = "LoveIt"
#theme = "docsy"
#theme = "ananke"

[params]
author = "JunSeung Cho"
